import { Layout, MainLayout } from '@components/common/layout';
import { SEO } from '@components/common/seo';
import type { ReactElement, ReactNode } from 'react';

export default function Home(): JSX.Element {
  return (
    <main
      className='flex min-h-screen w-full max-w-xl flex-col items-center 
                 border-x border-border-color p-4'
    >
      <SEO title='Home / Twitter' description='Generated by create next app.' />
      <h1 className='text-xl font-bold'>Hello World</h1>
    </main>
  );
}

Home.getLayout = (page: ReactElement): ReactNode => (
  <Layout>
    <MainLayout>{page}</MainLayout>
  </Layout>
);
