import { Layout } from '@components/common/layout';
import { SEO } from '@components/common/seo';

export default function Home(): JSX.Element {
  return (
    <Layout>
      <main>
        <SEO
          title='Next.js Template'
          description='Generated by create next app.'
        />
        <h1>Hello World</h1>
      </main>
    </Layout>
  );
}
