import { SEO } from '@components/common/seo';

export default function Messages(): JSX.Element {
  return (
    <main
      className='flex min-h-screen max-w-5xl flex-1 flex-col 
                 items-center justify-center border border-border-color p-4'
    >
      <SEO title='Home / Twitter' description='Generated by create next app.' />
      <h1 className='text-xl font-bold'>Hello World</h1>
    </main>
  );
}
